version: 2

builds:
  - main: .
    binary: seshat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^test:"

release:
  github:
    owner: tardanoir
    name: seshat

homebrew_casks:
  - repository:
      owner: tardanoir
      name: homebrew-tap
    homepage: "https://github.com/tardanoir/seshat"
    description: "A lightweight TUI SQL client for PostgreSQL"
    license: "MIT"

nfpms:
  - package_name: seshat
    homepage: "https://github.com/tardanoir/seshat"
    maintainer: "tardanoir"
    description: "A lightweight TUI SQL client for PostgreSQL"
    license: "MIT"
    formats:
      - deb
      - rpm

# TODO: setup the aur for yay install
# aurs:
#   - name: seshat-bin
#     homepage: "https://github.com/tardanoir/seshat"
#     description: "A lightweight TUI SQL client for PostgreSQL"
#     maintainers:
#       - "tardanoir"
#     license: "MIT"
#     private_key: "{{ .Env.AUR_KEY }}"
#     git_url: "ssh://aur@aur.archlinux.org/seshat-bin.git"
